In [1]:
import numpy as np

### Часть 1

#### Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

**а)**

Матрица А: $m = 4$, $n = 2$

Матрица B: $m = 4$, $n = 2$

$A \cdot B$ не определено, т.к. $n_A \neq m_B$

$B \cdot A$ не определено, т.к. $n_B \neq m_A$

In [2]:
A = np.random.randint(100, size=(4,2))
B = np.random.randint(100, size=(4,2))

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[64 37]
 [57 53]
 [23 46]
 [69 37]]
Матрица B
[[ 2 54]
 [63 24]
 [79 72]
 [40 34]]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

Как видно, python выдаёт соответствующую ошибку.

**б)**

Матрица А: $m = 2$, $n = 5$

Матрица B: $m = 5$, $n = 3$

$A \cdot B$ определено, т.к. $n_A = m_B$, размерность $AB$ равна $2 x 3$

$B \cdot A$ не определено, т.к. $n_B \neq m_A$

In [3]:
A = np.random.randint(100, size=(2,5))
B = np.random.randint(100, size=(5,3))

In [4]:
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[17 48 68 44 38]
 [65 63 89 59 44]]
Матрица B
[[39 10 78]
 [12 65 20]
 [77 93 76]
 [88 87 24]
 [61 36  0]]
Матрица AB
[[12665 14810  8510]
 [18020 19739 14510]]


ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

Как видно, python выдаёт соответствующую ошибку.

**в)**

Матрица А: $m = 8$, $n = 3$

Матрица B: $m = 3$, $n = 8$

$A \cdot B$ определено, т.к. $n_A = m_B$, размерность $AB$ равна $8 x 8$

$B \cdot A$ определено, т.к. $n_B = m_A$, размерность $AB$ равна $3 x 3$

In [5]:
A = np.random.randint(100, size=(8,3))
B = np.random.randint(100, size=(3,8))

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[42 73 32]
 [ 9 99 16]
 [58 68 73]
 [97 19 93]
 [79 98 24]
 [65 73  5]
 [40 11 97]
 [77 86 65]]
Матрица B
[[96 35 99 34 12 97 93 81]
 [46 17 66 45  8 70 92 89]
 [79 57 54 39 68 55 30 54]]
Матрица AB
[[ 9918  4535 10704  5961  3264 10944 11582 11627]
 [ 6682  2910  8289  5385  1988  8683 10425 10404]
 [14463  7347 14172  7879  6204 14401 13840 14692]
 [17533  9019 15879  7780  7640 15854 13559 14570]
 [13988  5799 15585  8032  3364 15843 17083 16417]
 [ 9993  3801 11523  5690  1704 11690 12911 12032]
 [12009  7116  9924  5638  7164  9985  7642  9457]
 [16483  7862 16809  9023  6032 17064 17023 17401]]
Матрица BA
[[30597 34097 29080]
 [25993 24944 25998]
 [25051 31476 19336]]


**г)**

Матрица А: $m = 4$, $n = 4$

Матрица B: $m = 4$, $n = 4$

$A \cdot B$ определено, т.к. $n_A = m_B$, размерность $AB$ равна $4 x 4$

$B \cdot A$ определено, т.к. $n_B = m_A$, размерность $AB$ равна $4 x 4$

In [6]:
A = np.random.randint(100, size=(4,4))
B = np.random.randint(100, size=(4,4))

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[88 23 50 30]
 [80 14 28 88]
 [59 45 88 99]
 [ 4  3 96 67]]
Матрица B
[[69 18 13 90]
 [21 99 50 93]
 [30  2  0 67]
 [60 80 85 96]]
Матрица AB
[[ 9855  6361  4844 16289]
 [11934  9922  9220 18826]
 [13596 13613 11432 24895]
 [ 7239  5921  5897 13503]]
Матрица BA
[[ 8639  2694 13738 10971]
 [13090  4398 17150 20523]
 [ 3068   919  7988  5565]
 [17079  6613 21936 23687]]


#### 2. Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

Сумма (поэлементно складываем значения, т.е. значение из 1-й строки 1-го столбца 1-й матрицы со значением из 1-й строки 1-го столбца 2-й матрицы и т.д.):

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$$

Произведение (произведение значений 1-й строки 1-го столбца 1-й матрицы и 1-й строки 1-го столбца 2-й матрицы складываем спроизведением значений 1-й строки 2-го столбца 1-й матрицы и 2-й строки 1-го столбца 2-й матрицы и т.д.):
$$A\cdot B=\begin{pmatrix}
1\cdot4+(-2)\cdot0 & 1\cdot(-1)+(-2)\cdot5\\ 
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$$

$$B\cdot A=\begin{pmatrix}
4\cdot1+(-1)\cdot3 & 4\cdot(-2)+(-1)\cdot0\\ 
0\cdot1+5\cdot3 & 0\cdot(-2)+5\cdot0
\end{pmatrix}=\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}.$$

In [7]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'А + В\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
А + В
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


#### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3\cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4\cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3\cdot 1 & 3\cdot 7\\ 
3\cdot 3 & 3\cdot (-6)
\end{pmatrix} - \begin{pmatrix}
2\cdot 0 & 2\cdot 5\\ 
2\cdot 2 & 2\cdot (-1)
\end{pmatrix} + \begin{pmatrix}
4\cdot 2 & 4\cdot (-4)\\ 
4\cdot 1 & 4\cdot 1
\end{pmatrix}= \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$$

In [8]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np. array([[2, -4], [1, 1]])

print(f'Линейная комбинация 3А - 2В + 4С для матриц А, В и С равна\n{3*A - 2*B + 4*C}')

Линейная комбинация 3А - 2В + 4С для матриц А, В и С равна
[[ 11  -5]
 [  9 -12]]


#### 4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [9]:
A = np.array([[4,1], [5, -2], [2, 3]])
print(f'Матрица A\n{A}')
A_t = A.T
print(f'Матрица A_t\n{A_t}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица A_t
[[ 4  5  2]
 [ 1 -2  3]]


In [10]:
print(f'Произведение матриц А и A_t\n{A @ A_t}')
print(f'Произведение матриц A_t и А\n{A_t @ A}')

Произведение матриц А и A_t
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Произведение матриц A_t и А
[[45  0]
 [ 0 14]]


#### 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy

In [11]:
def matrix_product():
    # Вводим размер матриц
    r1 = int(input('Строк в матрице 1: '))
    c1 = int(input('Столбцов в матрице 1: '))
    r2 = int(input('Строк в матрице 2: '))
    c2 = int(input('Столбцов в матрице 2: '))

    print('Вводим элементы матрицы A')
    # Вводим элементы матрицы A
    A = []
    for i in range(r1):
        A.append([])
        for j in range(c1):
            A[i].append(int(input()))
    print('A = ')
    for q in A:
        print(q)
    print('Вводим элементы матрицы B')
    # Вводим элементы матрицы B
    B = []
    for q in range(r2):
        B.append([])
        for w in range(c2):
            B[q].append(int(input()))
    print('B = ')
    for q in B:
        print(q)

    # Умножение
    s = 0  # сумма
    t = []  # временная матрица
    C = []  # конечная матрица
    if len(B) != len(A[0]):
        print('Матрицы не могут быть перемножены')
    else:
        r1 = len(A)  # количество строк в первой матрице
        c1 = len(A[0])  # количество столбцов в первой матрице
        r2 = c1  # количество строк во второй матрице
        c2 = len(B[0])  # количество столбцов во второй матрице
        for z in range(0, r1):
            for j in range(0, c2):
                for i in range(0, c1):
                    s = s + A[z][i] * B[i][j]
                t.append(s)
                s = 0
            C.append(t)
            t = []
    print(f'Произведение матриц равно: {C}')

matrix_product()

Строк в матрице 1: 2
Столбцов в матрице 1: 3
Строк в матрице 2: 3
Столбцов в матрице 2: 4
Вводим элементы матрицы A
5
9
10
-4
5
3
A = 
[5, 9, 10]
[-4, 5, 3]
Вводим элементы матрицы B
6
9
11
-4
-3
8
28
5
1
-9
7
12
B = 
[6, 9, 11, -4]
[-3, 8, 28, 5]
[1, -9, 7, 12]
Произведение матриц равно: [[13, 27, 377, 145], [-36, -23, 117, 77]]


### Часть 2

#### 1. Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

а) $$det A = sin x\cdot sin x - (-cos x)\cdot cos x = sin^2 x + cos^2 x = 1$$

б)

$det A = (-1)^2 \cdot 4\cdot
$$\begin{vmatrix}
5 & 1\\ 
9 & 0
\end{vmatrix};$$ + 0 + 0 = 4\cdot (5\cdot 9 - 0) = 180$

In [12]:
A = np.array([[4, 2,3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель матрицы равен:\n{np.linalg.det(A):.0f}')

Определитель матрицы равен:
180


в)

$det A = (-1)^2 \cdot 1\cdot
$$\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix} + (-1)^3 \cdot 4\cdot
$$\begin{vmatrix}
2 & 3\\ 
8 & 9
\end{vmatrix} + (-1)^4 \cdot 7\cdot
$$\begin{vmatrix}
2 & 3\\ 
5 & 6
\end{vmatrix} = (5\cdot 9 - 6\cdot 8) - 4\cdot (2\cdot 9 - 3\cdot 8) + 7\cdot (2\cdot 6 - 3\cdot 5) = 0$

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель матрицы равен:\n{np.linalg.det(A):.0f}')

Определитель матрицы равен:
0


#### 2. Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $det(A^{2}) = det(A\cdot A) = det(A)\cdot det(A) = 16$ *по 9-му свойству определителя*

По определению определителя матрицы, матрица А является квадратной.

б) $det(A^{T}) = det(A) = 4$ *по 1-му свойству определителя*

в) $det(2A) = 2^{n}det(A) = 2^{n+2}$ *по 2-му свойству определителя*
где $n$ - количество столбцов в матрице $A$

#### 3. Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица называется вырожденной, если её определитель равен нулю.
Поскольку выше уже был ручной подсчёт определителя, воспользуемся numpy.

In [14]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель матрицы равен:\n{np.linalg.det(A):.0f}')

Определитель матрицы равен:
0


**Ответ:** так как $det A = 0$, матрица $A$ является вырожденной.

#### 4. Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) Как можно заметить, третья строка является суммой двух верхних, следовательно, её можно откинуть.
Для вычисления ранга приведем матрицу к ступенчатому виду, используя элементарные преобразования над строками и столбцами матрицы.
от 2 строки отнимаем 1 строку:
$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix};$

И делим её на -1:
$\begin{pmatrix}
1 & 2 & 3\\ 
0 & 1 & 2
\end{pmatrix};$

**Ответ:** Так как ненулевых строк 2, ранг матрицы равен 2

In [15]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(A)

2

б) Как и в предыдущем примере, третья строка является суммой двух верхних, следовательно, её можно откинуть.
Значит $A`$ имеет вид $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\  
2 & 3 & 5 & 6
\end{pmatrix}.$

Для вычисления ранга приведем матрицу к ступенчатому виду, используя элементарные преобразования над строками и столбцами матрицы.

Делим 3-ю строку на 2:
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\  
1 & 1.5 & 2.5 & 3
\end{pmatrix}.$

Делим 2-ю строку на 2:
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 1 & 1\\  
1 & 1.5 & 2.5 & 3
\end{pmatrix}.$

От 1-й строки отнимаем 2 строку, умноженную на 2: $\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 1 & 1\\  
1 & 1.5 & 2.5 & 3
\end{pmatrix}.$

И умеожаем её на -1: $\begin{pmatrix}
0 & 0 & 0 & 1\\ 
0 & 0 & 1 & 1\\  
1 & 1.5 & 2.5 & 3
\end{pmatrix}.$

**Ответ:** так как ненулевых строк три, то ранг матрицы равен 3.

In [16]:
A = np.array([[0, 0, 2,1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(A)

3