### Часть 1

In [1]:
import numpy as np

#### 1. Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Запишем расширенную матрицу системы:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Вычтем из третей строки первую:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Далее вычтем из второй строки первую, умноженную на 2:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Полученная система будет иметь вид:

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$

Решив третье уравнение, получим:

$x_{3} = \frac{3}{2}x_{4} - 2$

Подставляем полученное значение в систему:

$-x_{2}+\frac{3}{2}x_{4} - 2+5x_{4}=-2$

$x_{2} = 6.5x_{4}$

$x_{1}+6.5x_{4}-\frac{3}{2}x_{4}-2x_{4}=0$

$x_{1} = 3 x_{4}$

Производим замену.
Система имеет бесконечное число решений, общеее решение выглядит так:
    
$\begin{cases}
x_{4} = С, \\
x_{3} = \frac{3}{2}C - 2, \\
x_{2} = 6.5C, \\
x_{1} = 3C.
\end{cases}$

Частное решение, например, $C = 0$ будет выглядить так:

$\begin{cases}
x_{1} = 0, \\
x_{2} = 0, \\
x_{3} = - 2, \\
x_{4} = 0.
\end{cases}$

#### 2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [2]:
# a)

A = np.array([[3, -1, 1], [2, -5, -3], [1, 1,-1]])
A_ = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1,-1, 0]])
rank_a = np.linalg.matrix_rank(A)
rank_a_ = np.linalg.matrix_rank(A_)

print(f'Ранг обычной матрицы равен {rank_a}')
print(f'Ранг расширенной матрицы равен {rank_a_}')

Ранг обычной матрицы равен 3
Ранг расширенной матрицы равен 3


По скольку ранги у обычной и расширенной матриц равны, то СЛАУ совместна.

Так как $rang A = rang \widetilde{A} = n$ , где $n$ - кол-во неизвестных, то СЛАУ является определённой (имеет ровно одно решение).

In [3]:
# б)

А = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A_ = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
rank_a = np.linalg.matrix_rank(A)
rank_a_ = np.linalg.matrix_rank(A_)

print(f'Ранг обычной матрицы равен {rank_a}')
print(f'Ранг расширенной матрицы равен {rank_a_}')

Ранг обычной матрицы равен 3
Ранг расширенной матрицы равен 2


Так как $rang A\neq rang \widetilde{A}$, то СЛАУ несовместна (не имеет решений).

In [4]:
# в)

A = np.array([[1, 2, 5], [3, 1, -8]])
A_ = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
rank_a = np.linalg.matrix_rank(A)
rank_a_ = np.linalg.matrix_rank(A_)

print(f'Ранг обычной матрицы равен {rank_a}')
print(f'Ранг расширенной матрицы равен {rank_a_}')

Ранг обычной матрицы равен 2
Ранг расширенной матрицы равен 2


Так как $rang A = rang \widetilde{A} < n$ , где $n$ - кол-во неизвестных, то СЛАУ является неопределённой (имеет бесконечное количество решений).

#### 3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
A_ = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
rank_a = np.linalg.matrix_rank(A)
rank_a_ = np.linalg.matrix_rank(A_)

print(f'Ранг обычной матрицы равен {rank_a}')
print(f'Ранг расширенной матрицы равен {rank_a_}')

Ранг обычной матрицы равен 4
Ранг расширенной матрицы равен 4


Так как $rang A = rang \widetilde{A} = n$ , где $n$ - кол-во неизвестных, то СЛАУ является определённой (имеет ровно одно решение).

#### 4. Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank_a = np.linalg.matrix_rank(A)

print(f'Ранг обычной матрицы равен {rank_a}')

Ранг обычной матрицы равен 2


Исходя из теоремы Кронекера-Капелли, чтобы система была несовместимо необходимо выполнение неравенства $rang A\neq rang \widetilde{A}$.

В данном случае $rang \widetilde{A}$ должен быть не меньше 2.

Преобразуем матрицу $\widetilde{A}$ к ступенчатой форме:

Вычтем из второй строки первую, помноженную на 2, затем вычтем из третей строки первую, помноженную на 3:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c - 3a
\end{matrix}
\end{pmatrix}.$

Следующим действием вычтем из третей строки вторую, помноженную на 2:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c + a - 2b
\end{matrix}
\end{pmatrix}.$

Если $c + a - 2b\neq 0$, то СЛАУ является несовместной. Иначе одна из неизвестных является свободной переменной, а, следовательно, СЛАУ имеет бесконечное множество решений.

### Часть 2

#### 1. Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [7]:
# а)

A = np.array([[1, -2], [3, -4]])
A_2 = np.array([[1, -2], [7, -4]])
A_3 = np.array([[1, 1], [3, 7]])

det_a = np.linalg.det(A)
det_a2 = np.linalg.det(A_2)
det_a3 = np.linalg.det(A_3)

In [8]:
print(f'Определитель матрицы А: {det_a:.0f}')
print(f'Определитель матрицы А_2: {det_a2:.0f}')
print(f'Определитель матрицы А_3: {det_a3:.0f}')

Определитель матрицы А: 2
Определитель матрицы А_2: 10
Определитель матрицы А_3: 4


In [9]:
print(f'Ответ:\n x_1 равен {det_a2 / det_a:.0f}\n x_2 равен {det_a3 / det_a:.0f}')

Ответ:
 x_1 равен 5
 x_2 равен 2


In [10]:
# б)

A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
A_2 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
A_3 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
A_4 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])

det_a = np.linalg.det(A)
det_a2 = np.linalg.det(A_2)
det_a3 = np.linalg.det(A_3)
det_a4 = np.linalg.det(A_4)

print(f'Определитель матрицы А: {det_a:.0f}')
print(f'Определитель матрицы А_2: {det_a2:.0f}')
print(f'Определитель матрицы А_3: {det_a3:.0f}')
print(f'Определитель матрицы А_4: {det_a4:.0f}')

Определитель матрицы А: 43
Определитель матрицы А_2: 86
Определитель матрицы А_3: -43
Определитель матрицы А_4: 43


In [11]:
print(f'Ответ:\n x_1 равен {det_a2 / det_a:.0f}\n x_2 равен {det_a3 / det_a:.0f}\n x_3 равен {det_a4 / det_a:.0f}')

Ответ:
 x_1 равен 2
 x_2 равен -1
 x_3 равен 1


#### 2. Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а) Начнем прямой ход метода Гаусса. Для этого домножим первую строку на  2  и вычтем ее из второй строки. При этом запишем в матрицу  $L$  на место элемента  $l_{21}$  значение  2 . Затем нам нужно вычесть из третьей строки первую, домноженную на  3 . Значит, в матрицу  $L$  запишем  $l_{31} = 3$ .

Матрица коэффициентов будет иметь вид

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$

А матрица $L$ -

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}$

Далее умножим вторую строку на $4$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $4$.

В итоге получим

$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix},$

$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.$

б) Начнем прямой ход метода Гаусса. Для этого домножим первую строку на  2  и вычтем ее из второй строки. При этом запишем в матрицу  $L$  на место элемента  $l_{21}$  значение  2 . Затем нам нужно вычесть из третьей строки первую, домноженную на  3 . Значит, в матрицу  $L$  запишем  $l_{31} = 3$ , а из четвёртой первую, домноженную на 4, в матрицу  $L$  запишем  $l_{41} = 4$

Матрица коэффициентов будет иметь вид

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$

А матрица $L$ -

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & l_{32} & 1 & 0 \\
4 & l_{42} & l_{43} & 1 
\end{pmatrix}$

Далее умножим вторую строку на $5$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $5$. Затем умножим вторую строку на $6$ и вычтем её из четвёртой, при этом в матрицу $L$ на место $l_{42}$ запишем $6$

В итоге получим:

Матрица коэффициентов будет иметь вид

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$

А матрица $L$ -

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & l_{43} & 1 
\end{pmatrix}$

Далее умножим третью строку на $7$ и вычтем ее из четвёртой. При этом в матрицу $L$ на место $l_{43}$ запишем $7$.

В итоге получим:

$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix},$

$L=\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}.$

#### 3. Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Матрица коэффициентов имеет вид

$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$

Начнем прямой ход метода Гаусса. Для этого домножим первую строку на  $5.5$  и вычтем ее из второй строки. При этом запишем в матрицу  $L$  на место элемента  $l_{21}$  значение  $5.5$ . Затем нам нужно вычесть из третьей строки первую, домноженную на  $4.5$ . Значит, в матрицу  $L$  запишем  $l_{31} = 4.5$ .

Матрица коэффициентов будет иметь вид

$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 3.5 & -9.5
\end{pmatrix}$

А матрица $L$ -

$\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & l_{32} & 1
\end{pmatrix}$

Далее умножим первую строку на $3.5$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $3.5$.

В итоге получим

$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & -20
\end{pmatrix},$

$L=\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & 3.5 & 1
\end{pmatrix}.$

Теперь решим систему $Ly = b$

$\begin{cases}
y_{1} = 1 \\
5.5y_{1} + y_{2} = -6 \\
4.5y_{1} + 3.5y_{2} + y_{3} = -5
\end{cases}$

$\begin{cases}
y_{1} = 1 \\
y_{2} = -11.5 \\
y_{3} = 30.75
\end{cases}$

Теперь решим систему $Ux = y$

$\begin{cases}
2x_{1} + x_{2} + 3x_{3} = 1 \\
1.5x_{2} - 11.5x_{3} = -11.5 \\
-20x_{3} = 30.75
\end{cases}$

$\begin{cases}
x_{1}= 12,530(3) \\
x_{2} = -19.4541(6) \\
x_{3} = -1.5375
\end{cases}$

При проверке, подставив полученные значения в исходную систему, получаются равенства, а значит, найденное решение верно.

#### 4. Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Матрица коэффициентов будет иметь вид

$\begin{pmatrix}
81 & -45 & 45 \\ 
-45 & 50 & -15 \\ 
45 & -15 & 38
\end{pmatrix}$

Произведем разложение на $LL^{T}$:

$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9,$

$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$

$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$


$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=\sqrt{50 - 25} = 5,$

$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5\right )=2,$

$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$

Получили матрицы 

$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \;$


$L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$

Решим систему $Ly=b$

$\begin{cases}
9y_{1}=531 \\
-5y_{1}+5y_{2}=-460 \\
5y_{1}-2y_{2}+3y_{3}=193
\end{cases}$

$\begin{cases}
y_{1}=59 \\
y_{2}=-33 \\
y_{3}=-12
\end{cases}$

Решим систему $L^{T}x=y$

$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59 \\
5x_{2}+2x_{3}=-33 \\
3x_{3}=-12
\end{cases}$

$\begin{cases}
x_{1}=6 \\
x_{2}=-5 \\
x_{3}=-4
\end{cases}$

Проверим полученные результаты, подставив их в изначальную систему:

$\begin{cases}
81\cdot6-45\cdot(-5)+45\cdot(-4)=531 \\
-45\cdot6+50\cdot(-5)-15\cdot(-4)=-460 \\
45\cdot6-15\cdot(-5)+38\cdot(-4)=193
\end{cases}$

$\begin{cases}
531=531 \\
-460=-460 \\
193=193
\end{cases}$

#### 5. Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [12]:
#Минор
def submatrix(M,c):
    B = [[1]*len(M) for i in range(len(M))]
    for l in range(len(M)):
        for k in range(len(M)):
            B[l][k] = M[l][k]
    
    B.pop(0)
    
    for i in range(len(B)):
        B[i].pop(c)
    return B

#Определитель методом Лапласа
def det_L(M):
    X = 0
    if len(M) != len(M[0]):
        print('Матрица не квадратная')
    else:
        if len(M)<=2:
            return M[0][0] * M[1][1] - M[0][1] * M[1][0]
        else:
            for i in range(len(M)):
                X = X + ((-1)**i)*M[0][i]*det_L(submatrix(M,i))
        return X

#Решение методом Крамера
def Kramer(A,B):
    det_A = det_L(A)
    X = []
    if det_A == 0:
        print('Определитель матрицы не должен быть равен 0')
        return X
    n = len(A)    
    for i in range(n):
        matrix = A.copy()
        matrix[:,i] = B
        print('\n',matrix)
        X.append(det_L(matrix) / det_A)
    return X
    
#a = np.random.rand(3,3)
#b = np.random.rand(1,3)
a = np.array([[1,-2],[3,-4]])
b = np.array([1,7])
print(a)
print('\n',b)
print('\n', det_L(a))
print('\n', Kramer(a,b))

[[ 1 -2]
 [ 3 -4]]

 [1 7]

 2

 [[ 1 -2]
 [ 7 -4]]

 [[1 1]
 [3 7]]

 [5.0, 2.0]
